name: dj_music_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgroundpic.jpg
    - assets/images/djpic.png
    - assets/images/drumpad.png
    - assets/images/cutter.png
    - assets/images/mixer.png
    - assets/images/merger.png
    - assets/images/library.png
    - assets/images/setting.png